language: node_js
sudo: false
node_js:
- 10.9.0
branches:
  only:
  - master
  - develop
script:
  - if [ $TRAVIS_BRANCH = 'develop' ]; "BUNDLE_TYPE=app DATABASE_HOST=https://sandbox-sidebet-api.herokuapp.com node scripts/build.js" fi
  - if [ $TRAVIS_BRANCH = 'master' ]; "BUNDLE_TYPE=app DATABASE_HOST=https://sidebet-api.herokuapp.com node scripts/build.js" fi
before_deploy:
  - "cp -rf build/ deploy && cp static.json deploy/ && cd deploy/ && git add . && git commit -m 'deploy'"
deploy:
  provider: heroku
  api_key:
    secure: ${HEROKU_API_KEY}
  app:
    master: "sidebet-client"
    develop: "sandbox-sidebet-client"