language: node_js
sudo: false
node_js:
- 10.9.0
branches:
  only:
  - master
  - develop
script:
  - $TRAVIS_BRANCH == "develop" && BUNDLE_TYPE=app DATABASE_HOST=${HEROKU_SANDBOX_URL} node scripts/build.js
  - $TRAVIS_BRANCH == "master" && BUNDLE_TYPE=app DATABASE_HOST=${HEROKU_PRODUCTION_URL} node scripts/build.js
before_deploy:
  - "cp -rf build/ deploy && cp static.json deploy/ && cd deploy/ && git add . && git commit -m 'deploy'"
deploy:
  provider: heroku
  api_key:
    secure: ${HEROKU_API_KEY}
  app:
    master: "sidebet-client"
    develop: "sandbox-sidebet-client"